import { createClient } from "@supabase/supabase-js";
import cookieParser from "cookie-parser";
import cors from "cors";
import express from "express";
import rateLimit from "express-rate-limit";
import helmet from "helmet";
import pinoHttp from "pino-http";
import authRoutes from "./auth/auth.routes";
import { ValidationError } from "./errors/AppError";
import { errorHandler, notFoundHandler } from "./errors/errorHandler";
import { logger } from "./logger";
import adminProjectsRoutes from "./projects/projects.routes";
import { asyncHandler } from "./utils/asyncHandler";

const app = express();

app.use(pinoHttp({ logger }));

/* security & parsers */
app.use(helmet());
app.use(express.json());
app.use(cookieParser());

/* CORS*/
app.use(
	cors({
		origin: "http://localhost:5173",
		credentials: true,
	}),
);

app.use(
	rateLimit({
		windowMs: 15 * 60 * 1000,
		max: 200,
	}),
);

app.get("/", (_req, res) => {
	res.json({ message: "Welcome to my Portfolio API" });
});

/* health */
app.get("/health", (_req, res) => {
	res.json({ ok: true });
});

const supabaseUrl = process.env.SUPABASE_URL;
const supabaseServiceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!supabaseUrl || !supabaseServiceRoleKey) {
	throw new Error("Missing required Supabase environment variables");
}

const supabase = createClient(supabaseUrl, supabaseServiceRoleKey);

/* public */
app.get(
	"/projects",
	asyncHandler(async (_req, res) => {
		const { data, error } = await supabase
			.from("projects")
			.select("*")
			.order("created_at", { ascending: false });

		if (error) {
			logger.error(error, "Error fetching projects from Supabase");
			throw new Error("Failed to fetch projects");
		}

		res.json(data);
	}),
);

app.post(
	"/projects",
	asyncHandler(async (req, res) => {
		const { title, description, image_url, github_url, live_url, tags } =
			req.body;

		if (!title) {
			throw new ValidationError("title is required");
		}

		const { data, error } = await supabase
			.from("projects")
			.insert([{ title, description, image_url, github_url, live_url, tags }])
			.select()
			.single();

		if (error) {
			logger.error(error, "Error creating project in Supabase");
			throw new Error(error.message);
		}

		// data includes id + created_at generated by DB
		res.status(201).json(data);
	}),
);

/* auth + admin */
app.use("/auth", authRoutes);
app.use("/admin/projects", adminProjectsRoutes);

/* error handlers - must be last */
app.use(notFoundHandler);
app.use(errorHandler);

export default app;
