import { createClient } from "@supabase/supabase-js";
import cookieParser from "cookie-parser";
import cors from "cors";
import express from "express";
import rateLimit from "express-rate-limit";
import helmet from "helmet";
import pinoHttp from "pino-http";
import authRoutes from "./auth/auth.routes";
import { ValidationError } from "./errors/AppError";
import { errorHandler, notFoundHandler } from "./errors/errorHandler";
import { logger } from "./logger";
import adminProjectsRoutes from "./projects/projects.routes";
import { asyncHandler } from "./utils/asyncHandler";

const app = express();

app.use(pinoHttp({ logger }));

/* security & parsers */
app.use(helmet());
app.use(express.json());
app.use(cookieParser());

/* CORS*/
app.use(
	cors({
		origin: "http://localhost:5173",
		credentials: true,
	}),
);

app.use(
	rateLimit({
		windowMs: 15 * 60 * 1000,
		max: 200,
	}),
);

app.get("/", (_req, res) => {
	res.json({ message: "Welcome to my Portfolio API" });
});

/* health */
app.get("/health", (_req, res) => {
	res.json({ ok: true });
});

const supabaseUrl = process.env.SUPABASE_URL;
const supabaseServiceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!supabaseUrl || !supabaseServiceRoleKey) {
	throw new Error("Missing required Supabase environment variables");
}

const supabase = createClient(supabaseUrl, supabaseServiceRoleKey);

/* public */
app.get(
	"/projects",
	asyncHandler(async (req, res) => {
		// Parse query parameters for pagination
		const page = Number.parseInt(req.query.page as string, 10) || 1;
		const limit = Number.parseInt(req.query.limit as string, 10) || 10;
		const offset = (page - 1) * limit;

		// Get total count for pagination
		const { count, error: countError } = await supabase
			.from("projects")
			.select("*", { count: "exact", head: true });

		if (countError) {
			logger.error(countError, "Error counting projects from Supabase");
			throw new Error("Failed to count projects");
		}

		// Fetch projects with pagination
		const { data, error } = await supabase
			.from("projects")
			.select("*")
			.order("created_at", { ascending: false })
			.range(offset, offset + limit - 1);

		if (error) {
			logger.error(error, "Error fetching projects from Supabase");
			throw new Error("Failed to fetch projects");
		}

		const totalCount = count || 0;

		// Structure the response
		res.json({
			success: true,
			data: data.map((project) => ({
				id: project.id,
				title: project.title,
				description: project.description,
				technologies: project.tags || [],
				images: {
					thumbnail: project.image_url,
				},
				links: {
					live: project.live_url,
					github: project.github_url,
				},
				metadata: {
					createdAt: project.created_at,
				},
			})),
			pagination: {
				currentPage: page,
				totalPages: Math.ceil(totalCount / limit),
				totalCount,
				perPage: limit,
				hasNextPage: page < Math.ceil(totalCount / limit),
				hasPreviousPage: page > 1,
			},
		});
	}),
);

app.post(
	"/projects",
	asyncHandler(async (req, res) => {
		const { title, description, image_url, github_url, live_url, tags } =
			req.body;

		if (!title) {
			throw new ValidationError("title is required");
		}

		const { data, error } = await supabase
			.from("projects")
			.insert([{ title, description, image_url, github_url, live_url, tags }])
			.select()
			.single();

		if (error) {
			logger.error(error, "Error creating project in Supabase");
			throw new Error(error.message);
		}

		// data includes id + created_at generated by DB
		res.status(201).json(data);
	}),
);

/* auth + admin */
app.use("/auth", authRoutes);
app.use("/admin/projects", adminProjectsRoutes);

/* error handlers - must be last */
app.use(notFoundHandler);
app.use(errorHandler);

export default app;
